openapi: "3.0.0"
info:
  version: 1.0.0
  title: COVID-19 API
  description: 北海道 新型コロナウイルスまとめサイト向けAPI
  contact:
    name: JUST Do It
    url: https://stopcovid19.hokkaido.dev/about/
  license:
    name: Attribution 4.0 International (CC BY 4.0)
    url: https://creativecommons.org/licenses/by/4.0/deed.ja

servers:
  - url: https://raw.githubusercontent.com/codeforsapporo/covid19hokkaido_scraping/gh-pages

tags:
  - name: 患者統計情報
    description: 患者統計情報

paths:
  /contacts.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        日付:
                          $ref: '#/components/schemas/日付'
                        曜日:
                          $ref: '#/components/schemas/曜日'
                        9-13時:
                          $ref: '#/components/schemas/9-13時'
                        13-17時:
                          $ref: '#/components/schemas/13-17時'
                        17-21時: 
                          $ref: '#/components/schemas/17-21時'
                        date:
                          $ref: '#/components/schemas/date'
                        w:
                          $ref: '#/components/schemas/w'
                        short_date:
                          $ref: '#/components/schemas/short_date'
                        小計:
                          $ref: '#/components/schemas/小計'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /current_patients.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        日付:
                          $ref: '#/components/schemas/日付'
                        患者数:
                          $ref: '#/components/schemas/患者数'
                        軽症中等症:
                          $ref: '#/components/schemas/軽症中等症'
                        重症:
                          $ref: '#/components/schemas/重症'
                        死亡: 
                          $ref: '#/components/schemas/死亡'
                        備考:
                          $ref: '#/components/schemas/備考'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /discharges_summary.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        日付:
                          $ref: '#/components/schemas/日付'
                        日治療終了数:
                          $ref: '#/components/schemas/日治療終了数'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /inspections.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        日付:
                          $ref: '#/components/schemas/日付'
                        日検査数:
                          $ref: '#/components/schemas/日検査数'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /last_update.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
           text/plain:
              schema:
                type: string
                format: date-time
                example: "2020-03-22T18:05:53.509909+09:00"

  /main_summary.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        検査人数:
                          $ref: '#/components/schemas/検査人数'
                        陽性者数:
                          $ref: '#/components/schemas/陽性者数'
                        患者数:
                          $ref: '#/components/schemas/患者数'
                        軽症・中等症者数:
                          $ref: '#/components/schemas/軽症・中等症者数'
                        重傷者数: 
                          $ref: '#/components/schemas/重傷者数'
                        死亡者数:
                          $ref: '#/components/schemas/死亡者数'
                        陰性確認数:
                          $ref: '#/components/schemas/陰性確認数'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /patients.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        No:
                          $ref: '#/components/schemas/No'
                        リリース日:
                          $ref: '#/components/schemas/リリース日'
                        曜日:
                          $ref: '#/components/schemas/曜日'
                        居住地:
                          $ref: '#/components/schemas/居住地'
                        年代: 
                          $ref: '#/components/schemas/年代'
                        性別:
                          $ref: '#/components/schemas/性別'
                        属性:
                          $ref: '#/components/schemas/属性'
                        備考:
                          $ref: '#/components/schemas/備考'
                        補足:
                          $ref: '#/components/schemas/補足'
                        退院:
                          $ref: '#/components/schemas/退院'
                        周囲の状況:
                          $ref: '#/components/schemas/周囲の状況'
                        濃厚接触者の状況:
                          $ref: '#/components/schemas/濃厚接触者の状況'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /patients_summary.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        日付:
                          $ref: '#/components/schemas/日付'
                        日陽性数:
                          $ref: '#/components/schemas/日陽性数'
                  last_update:
                    $ref: '#/components/schemas/last_update'

  /querents.json:
    get:
      tags:
        - 患者統計情報
      description: COVID-19感染患者数情報
      responses:
        '200':
          description: 患者統計情報
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        日付:
                          $ref: '#/components/schemas/日付'
                        曜日:
                          $ref: '#/components/schemas/曜日'
                        9-17時:
                          $ref: '#/components/schemas/9-17時'
                        17-翌9時:
                          $ref: '#/components/schemas/17-翌9時'
                        date:
                          $ref: '#/components/schemas/date'
                        w:
                          $ref: '#/components/schemas/w'
                        short_date:
                          $ref: '#/components/schemas/short_date'
                        小計:
                          $ref: '#/components/schemas/小計'


                  last_update:
                    $ref: '#/components/schemas/last_update'

components:
  schemas:
    日付:
      description: 日付
      type: string
      format: date-time
      example: 2020-01-28T00:00
    曜日:
      description: 曜日
      type: string
      example: 月
    患者数:
      description: 患者数
      type: integer
      example: 3
    軽症中等症:
      description: 軽症中等症
      type: integer
      example: 22
    重症:
      description: 重症
      type: integer
      example: 10
    死亡: 
      description: 死亡
      type: integer
      example: 10
    検査人数:
      description: 検査人数
      type: integer
      example: 10
    陽性者数: 
      description: 陽性者数
      type: integer
      example: 10
    日陽性数: 
      description: 日陽性数
      type: integer
      example: 10
    軽症・中等症者数: 
      description: 軽症・中等症者数
      type: integer
      example: 10
    重傷者数: 
      description: 重傷者数
      type: integer
      example: 10
    死亡者数: 
      description: 死亡者数
      type: integer
      example: 10
    陰性確認数: 
      description: 陰性確認数
      type: integer
      example: 10

    備考:
      description: 備考
      type: string
      example: 10

    9-13時:
      description: 9-13時
      type: integer
      example: ""
    13-17時:
      description: 9-13時
      type: integer
      example: ""
    17-21時:
      description: 9-13時
      type: integer
      example: ""
    9-17時:
      description: 9-17時
      type: integer
      example: ""
    17-翌9時:
      description: 17-翌9時
      type: integer
      example: ""
    date:
      description: 日付
      type: string
      example: 2020-02-19
    short_date:
      description: 日付
      type: string
      example: 02/19

    小計:
      description: 小計
      type: integer
      example: 350

    日治療終了数:
      description: 日治療終了数
      type: integer
      example: 1

    日検査数:
      description: 日検査数
      type: integer
      example: 1

    w:
      description: w
      type: string
      example: ""

    No:
      description: "No"
      type: integer
      example: 1

    リリース日:
      description: リリース日
      type: string
      format: date-time
      example: 2020-01-28T00:00

    居住地:
      description: 居住地
      type: string
      example: 札幌市

    年代:
      description: 年代
      type: string
      example: 40代

    性別:
      description: 性別
      type: string
      example: 女性

    属性:
      description: 属性
      type: string
      example: "自営業"

    補足:
      description: 補足
      type: string
      example: ""

    退院:
      description: 退院
      type: string
      example: ""

    周囲の状況:
      description: 周囲の状況
      type: string
      example: "なし"

    濃厚接触者の状況:
      description: 濃厚接触者の状況
      type: string
      example: "濃厚接触者を特定し 健康観察終了"


    last_update:
      type: string
      format: date-time
      example: 2020-03-22T01:08:05.250938+09:00